using 'main.bicep'

param location = 'Canada Central'
param vmName = 'mm-vm-workload'
param osDiskName = '${vmName}-disk'
param nicName = '${vmName}-nic'
param compName = 'workload'
param vmCount = 2
param userName = 'marek'
param userPassword = 'tobedefined'
param lbName = 'mm-lb'
param vnetName = 'mm-vnet'
param subnetWorkloadName = 'subnet-workload'
param subnetLbName = 'subnet-lb'
param nsgName = 'mm-nsg'
